### PR TITLE
Document Accio Support in README

### LINKED ISSUE #33: Add Accio support
I suggest to add support for [Accio](https://github.com/JamitLabs/Accio), a new dependency manager by simply adding a `Package.swift` file.

### PR DESCRIPTION
**Pull request by fredpi**
Closes #33 by adding a `Package.swift` manifest and documenting Accio support in the readme.

### CODE REVIEW

**Comment by fredpi** [comment]
Just found out that #32 is aiming to achieve basically the same ;) I will leave this open and rebase once #32 is merged, so my README can merged thereafter.

**Comment by huri000** [comment]
Thanks for your contribution.
#32 has been merged. As a result of that, there are conflicts with your PR source branch. After resolving them, I'll review this as well.

**Comment by fredpi** [comment]
@huri000 I just rebased to fix the conflicts 👍

**Comment by fredpi** [comment]
@huri000 Would you mind having a look at this again? ;)

**Pull request merged**
